
api_version = "2025-04"
[[extensions]]
name = "t:name"
handle = "cincopa-product-configure"
uid = "518b8773-2b9e-3cd9-db54-2a0944ca19b75ddf63cc"
type = "ui_extension"


# Both extension points are required
[[extensions.targeting]]
module = "./src/ProductDetailsConfigurationExtension.jsx"
target = "admin.product-details.configuration.render"
[extensions.targeting.urls]
edit = "/bundles/products/{product_id}"


[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.jsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.jsx)
target = "admin.product-variant-details.configuration.render"
